# Generated by Django 4.2.13 on 2024-06-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discountPercentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stock', models.IntegerField()),
                ('sku', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('warrantyInformation', models.CharField(choices=[('no_warranty', 'No warranty'), ('six_months_warranty', '6 months warranty'), ('one_week_warranty', '1 week warranty'), ('three_year_warranty', '3 year warranty'), ('three_months_warranty', '3 months warranty'), ('lifetime warranty', 'Lifetime warranty'), ('two_year_warranty', '2 year warranty'), ('one_month_warranty', '1 month warranty'), ('five_year_warranty', '5 year warranty'), ('one_year_warranty', '1 year warranty')], default='no_warranty', max_length=255)),
                ('shippingInformation', models.CharField(choices=[('ships_overnight', 'Ships overnight'), ('ships_in_2_weeks', 'Ships in 2 weeks'), ('ships_in_1_month', 'Ships in 1 month'), ('ships_in_3_5_business_days', 'Ships in 3-5 business days'), ('ships_in_1_2 business_days', 'Ships in 1-2 business days'), ('ships_in_1_week', 'Ships in 1 week')], default='ships_overnight', max_length=255)),
                ('availabilityStatus', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=255)),
                ('returnPolicy', models.CharField(choices=[('no_return_policy', 'No return policy'), ('thirty_days_return_policy', '30 days return policy'), ('ninety_days_return_policy', '90 days return policy'), ('sixty_days_return_policy', '60 days return policy'), ('seven_days_return_policy', '7 days return policy')], default='no_return_policy', max_length=255)),
                ('minimumOrderQuantity', models.IntegerField()),
                ('thumbnail', models.URLField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=255)),
                ('qrCode', models.URLField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField()),
                ('reviewerName', models.CharField(max_length=255)),
                ('reviewerEmail', models.EmailField(max_length=254)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
